@startuml MovePileToFoundation

hide empty description

state OPENED_GAME_UP as "OPENED_GAME"
state checkSource <<choice>>
state CheckDestination <<choice>>
state kingCard <<choice>>
state consecutiveCards <<choice>>
state sameSuiteCards <<choice>>
state OPENED_GAME_DOWN as "OPENED_GAME"

[*] --> OPENED_GAME_UP
OPENED_GAME_UP --> S1: Player asks to move a card from a foundation to a pile
S1 --> S2: System requires a source Pile
S2 --> S3: Player introduce a source Pile
S3 --> S4 : System requires a destination Foundation
S4 --> checkSource : Player introduces a destination Foundation

checkSource --> S6: [Source Pile is empty]
S6 -> OPENED_GAME_DOWN: System shows source pile empty error

checkSource --> CheckDestination : [Source Pile is **not** empty]

CheckDestination --> kingCard : [Destination Foundation is empty]

kingCard -> S5 : [source foundation card is a As]
kingCard --> S6 : [source foundation card is **not** a As]


CheckDestination --> consecutiveCards: [Destination Foundation is **not** empty]
consecutiveCards --> sameSuiteCards: [foundation card is the consecutive mayor\ncard of the destination pile card]
consecutiveCards -> S6

sameSuiteCards -down-> S5: [foundation card is the same\ncolour of the destination pile card]
sameSuiteCards -down-> S6
S5 --> OPENED_GAME_DOWN: System shows the card\nfacing up in the destination pile

OPENED_GAME_DOWN -->[*]

@enduml
