@startuml PileToFoundationUC

hide empty description

state OPENED_GAME_UP as "OPENED_GAME"
state emptyPile <<choice>>
state emptyFoundation <<choice>>
state asCard <<choice>>
state consecutiveCards <<choice>>
state sameSuiteCards <<choice>>
state OPENED_GAME_DOWN as "OPENED_GAME"

[*] --> OPENED_GAME_UP
OPENED_GAME_UP --> S1: Player asks to move a card from a pile to a foundation
S1 --> S2: System requires a source pile
S2 --> emptyPile: Player introduce a source pile
emptyPile --> S3
emptyPile --> S6: [pile.empty]
S6 --> OPENED_GAME_DOWN: System shows pile empty error
S3 -->  S4: System requires a destination foundation
S4 --> emptyFoundation: Player introduce a destination foundation
emptyFoundation --> asCard
asCard --> OPENED_GAME_DOWN: System shows invalid movement error
asCard --> S5: [pile card is an As]
emptyFoundation --> consecutiveCards: [foundation not empty]
consecutiveCards --> sameSuiteCards: [pile card is the consecutive mayor card of the destination foundation card]
consecutiveCards --> OPENED_GAME_DOWN: System shows invalid movement error
sameSuiteCards --> S5: [pile card is the same suit of the destination foundation card]
sameSuiteCards --> OPENED_GAME_DOWN: System shows invalid movement error
S5 --> OPENED_GAME_DOWN: System shows the card facing up in the destination foundation

OPENED_GAME_DOWN -->[*]

@enduml