@startuml
'https://plantuml.com/activity-diagram-beta

start

partition PileToPile {

repeat
   repeat
      :Player selects source **Pile**;
   repeat while (Pile.isEmpty) is (true)

   repeat
      :Player inputs number of cards \nto move;
   repeat while (Pile.size() < input) is (true)

   repeat
      :Player selects target **Pile**;
   repeat while (**ValidMoveChecker**) is (false)
repeat while (Player confirms move) is (false)

:Remove Cards from the source **Pile**;
:Assign Cards to the target **Pile**;
:Show Result;
:OPENED_GAME;
}

stop

@enduml
