@startuml
[*] --> Initial

state game_over <<choice>>

Initial --> OPENED_GAME : Start
OPENED_GAME -> CLOSED_GAME : Abort
OPENED_GAME -> game_over : MovePileToPile
OPENED_GAME -> game_over : MoveFoundationToPile
OPENED_GAME -> game_over : MoveWasteToFoundation
OPENED_GAME -> game_over : MoveWasteToPile
OPENED_GAME -> game_over : MovePileToFoundation
OPENED_GAME -> game_over : MoveStockToWaste
OPENED_GAME -> game_over : MoveWasteToStock

game_over --> CLOSED_GAME : [game_over]
game_over --> OPENED_GAME : [continue game]

CLOSED_GAME --> [*]
@enduml
