@startuml
[*] --> Initial

state game_over <<choice>>

Initial --> OPENED_GAME
OPENED_GAME -> CLOSED_GAME : Abort
OPENED_GAME -> game_over : move_card
game_over --> CLOSED_GAME : [game_over]
game_over --> OPENED_GAME

CLOSED_GAME --> [*]

@enduml
