@startuml UseCases
left to right direction

usecase "StartGame" as StartGame
usecase "MoveFromStockToWaste" as UC1
usecase "MoveFromWasteToFoundation" as UC2
usecase "MoveFromWasteToPile" as UC3
usecase "MoveFromPileToFoundation" as UC4
usecase "MoveFromPileToPile" as UC5
usecase "MoveFromFoundationToPile" as UC6
usecase "MoveFromWasteToStock" as UC7
usecase "ShowGame" as ShowGame
usecase "AbortGame" as AbortGame

Player --> StartGame
Player --> UC1
Player --> UC2
Player --> UC3
Player --> UC4
Player --> UC5
Player --> UC6
Player --> UC7
Player --> AbortGame

UC1 -.> ShowGame : include
UC2 -.> ShowGame : include
UC3 -.> ShowGame : include
UC4 -.> ShowGame : include
UC5 -.> ShowGame : include
UC6 -.> ShowGame : include
UC7 -.> ShowGame : include
@enduml
