@startuml
'https://plantuml.com/activity-diagram-beta

start
partition ValidMoveChecker {
   if (**targetGroup** is empty) then (false)
      :firstSource = **sourceGroup**.head;
      :lastTarget = **targetGroup**.tail;
      if (//nextCard//(lastTarget) == firstSource) then (true)
         if (**mustKeepColor**) then (true)
            :return //color//(lastTarget) == //color//(firstSource);
         else (false)
            :return //color//(lastTarget) != //color//(firstSource);
         endif
      else (false)
         :return **false**;
      endif
   else (true)
      :return **true**;
   endif
}

stop
@enduml
