@startuml
'https://plantuml.com/activity-diagram-beta

start

partition WasteToPile {

repeat
   :Player selects **Pile**;
repeat while (**ValidMoveChecker**) is (false)

:Assign Card to the **Pile**;
:OPENED_GAME;

stop

@enduml
