@startuml
'https://plantuml.com/activity-diagram-beta

start

partition WasteToFoundation {
:Player selects the upper card on **Waste** and move it to some Foundation;
repeat
   :Player selects **Foundation**;
repeat while (**ValidMoveChecker**) is (false)
:Assign Card to the **Foundation**;
:Show Result;

if (All **Foundation** are completed) then (yes)
   :[Game Over: Player **Wins**];
   :CLOSED_GAME;
else (false)
   :OPENED_GAME;
endif
}

stop

@enduml
