@startuml
'https://plantuml.com/activity-diagram-beta

start

partition WasteToFoundation {
:Player selects the upper card on **Waste** and move it to some Foundation;
repeat
   :Player selects **Foundation**;
repeat while (**ValidMoveChecker**) is (false)
:Assign Card to the **Foundation**;
:Show Result;
:OPENED_GAME;
}

stop

@enduml
