@startuml

package klondike.views #DDDDDD {
   class MoveFoundationToPileView
   class MovePileToFoundationView
   class MoveWasteToStockView
   class MoveWasteToPileView
   class MoveWasteToFoundationView

   class PileView
   class FoundationView
   class WasteView
   class StockView

   MoveFoundationToPileView -down-> PileView
   MoveFoundationToPileView -down-> FoundationView

   MovePileToFoundationView -down-> PileView
   MovePileToFoundationView -down-> FoundationView

   MoveWasteToStockView -down-> WasteView
   MoveWasteToStockView -down-> StockView
}

package "klondike.controllers" #DDDDDD {
   class MoveFoundationToPileController
   class MovePileToFoundationController
   class MovePileToPileController
   class MoveStockToWasteController
   class MoveWasteToStockController
   class MoveWasteToPileController
   class MoveWasteToFoundationController
}

package "klondike.models" #DDDDDD {
   enum Color {
      Red, Black
   }

   enum Suit {
    Hearts, Spades, Diamonds, Clubs
    Color getColor(Suit)
   }

   Card --> Suit
   Suit ..> Color

   Group -> "*" Card
   Group <|-down-- Pile
   Group <|-down-- Stock
   Group <|-down-- Waste
   Group <|-down- Foundation


   Tableaux *-down-> "7" Pile
   Klondike *-down-> "1" Stock
   Klondike *-down-> "1" Waste
   Klondike *-down-> "1" Tableaux
   Klondike *-down-> "4" Foundation

   Foundation --> Suit
}

klondike.views ..> klondike.controllers
klondike.controllers ..> klondike.models

@enduml
