@startuml
class MoveFoundationToPileView
class MoveFoundationToPileController
class Klondike
circle Player

Player ..> "Request" MoveFoundationToPileView

MoveFoundationToPileView --> FoundationView
note on link: int getFoundation()

MoveFoundationToPileView --> PileView
note on link: int getPile()

MoveFoundationToPileView ---->  MoveFoundationToPileController
note on link: bool apply(nfoundation, npile)

MoveFoundationToPileController --> Klondike
note on link: bool moveFoundationToPile(nfoundation, npile)

class Klondike {
   Foundation getFoundation(int nfoundation);
}

Klondike --> Tableaux
note on link: Pile getPile(npile)

Klondike --->  Foundation
note on link: bool isEmpty()\nCard getFirstCard()\nvoid removeFirstCard()

Klondike ---> Pile
note on link: bool isEmpty()\nCard getLastCard()\nvoid storeCard(Card)

Klondike --> Card
note on link: bool isConsecutiveMinor(Card)\nbool hasSameColor(Card)\nbool isAKing()

@enduml