@startuml
class MoveWasteToStockView
class MoveWasteToStockController
class Klondike
class Waste
class Stock
circle Player

Player ..> "Request" MoveWasteToStockView

MoveWasteToStockView --> MoveWasteToStockController
note on link: bool apply()

MoveWasteToStockController --> Klondike
note on link: bool moveWasteToStock()

Klondike --> Waste
note on link: bool isEmpty()\nCard getFirstCard()\nvoid removeFirstCard()

Klondike --> Stock
note on link: void storeCard(Card)

@enduml
