@startuml
class MovePileToFoundationView
class MovePileToFoundationController
class Klondike
circle Player

Player ..> "Request" MovePileToFoundationView

MovePileToFoundationView --> FoundationView
note on link: int getFoundation()\nvoid show(foundation)

MovePileToFoundationView --> PileView
note on link: int getPile()\nvoid show(pile)

MovePileToFoundationView ----> MovePileToFoundationController
note on link: bool apply(npile, nfoundation)

MovePileToFoundationController --> Klondike
note on link: bool movePileToFoundation(npile, nfoundation)\nPile getPile(npile)\nFoundation getFoundation(nfoundation)

class Klondike

Klondike --> Tableaux
note on link: Pile getPile(npile)

Klondike ---> Pîle
note on link: bool isEmpty()\nCard getFirstCard()\nvoid removeFirstCard()

Klondike ---> Foundation
note on link: bool isEmpty()\nCard getLastCard()\nvoid storeCard(Card)

Klondike --> Card
note on link: bool isConsecutiveMayor(Card)\nbool hasSameColor(Card)\nbool isAs()

@enduml