@startuml
class MoveWasteToStockView
class MoveWasteToStockController
class Klondike
class Waste
class Stock
circle Player

Player ..> "Request" MoveWasteToStockView

MoveWasteToStockView --> MoveWasteToStockController
note on link: bool apply()\nWaste getWaste()\nStock getStock()

MoveWasteToStockView --> WasteView
note on link: void show(Waste)

MoveWasteToStockView --> StockView
note on link: void show(Stock)

MoveWasteToStockController --> Klondike
note on link: bool moveWasteToStock()\nWaste getWaste()\nStock getStock()

Klondike --> Waste
note on link: bool isEmpty()\nCard getFirstCard()\nvoid removeFirstCard()

Klondike --> Stock
note on link: void storeCard(Card)

@enduml
