@startuml
class MovePileToFoundationView
class MovePileToFoundationController
class Klondike
circle Player

Player ..> "Request" MovePileToFoundationView

MovePileToFoundationView --> "int getFoundation()" FoundationView
MovePileToFoundationView --> "int getPile()" PileView

MovePileToFoundationView ----> "bool apply(npile, nfoundation)" MovePileToFoundationController

MovePileToFoundationController --> "bool movePileToFoundation(npile, nfoundation)" Klondike

class Klondike {
   Foundation getFoundation(int nfoundation);
}

Klondike --> "Pile getPile(npile)" Tableaux

Klondike ---> "bool isEmpty()\nCard getFirstCard()\nvoid removeFirstCard()" Pîle
Klondike ---> "bool isEmpty()\nCard getLastCard()\nvoid storeCard(Card)" Foundation

Klondike --> "bool isConsecutiveMayor(Card)\nbool hasSameColor(Card)\nbool isAs()" Card

@enduml