@startuml
class MovePileToPileView
class MovePileToPileController
class Klondike
class Pile
circle Player

Player ..> "Request" MovePileToPileView

MovePileToPileView --> MovePileToPileController
note on link: bool apply(Pile, Pile)

MovePileToPileController --> Klondike
note on link: bool movePileToPile(originPile, destPile)

MovePileToPileView --> Klondike
note on link: Pile getOriginPile(pileId) \nPile getDestinationPile(pileId)

MovePileToPileView --> PileView
note on link: void showPile(pileId)

Klondike --> Pile
note on link: Pile getPile(pileId)
@enduml
