@startuml
class MoveStockToWasteView
class MoveStockToWasteController
class Klondike
class Waste
class Stock
circle Player

Player ..> "Request" MoveStockToWasteView

MoveStockToWasteView --> Klondike
note on link: Stock getStock()\nWaste getWaste()

Klondike --> Stock
note on link: Stock getStock()\nbool removeFromStock()
Klondike --> Waste
note on link: Waste getWaste()\nbool addToWaste()

MoveStockToWasteView ----> MoveStockToWasteController
note on link: bool apply(Stock, Waste)

MoveStockToWasteController --> Klondike
note on link: bool moveCard(Stock, Waste)

MoveStockToWasteView --> WasteView
note on link: void showWaste()

MoveStockToWasteView --> StockView
note on link: void showStock()
@enduml
