@startuml
class MoveFoundationToPileView
class MoveFoundationToPileController
class Klondike
circle Player

Player ..> "Request" MoveFoundationToPileView

MoveFoundationToPileView --> "Foundation getFoundation()" FoundationView
MoveFoundationToPileView --> "Pile getPile()" PileView

MoveFoundationToPileView ----> "bool apply(Foundation, Pile)" MoveFoundationToPileController

MoveFoundationToPileController --> "bool moveCard(Foundation, Pile)" Klondike

@enduml