@startuml StockToWasteUC

hide empty description

state OPENED_GAME_UP as "OPENED_GAME"
state emptyStock <<choice>>
state emptyWaste <<choice>>
state OPENED_GAME_DOWN as "OPENED_GAME"

[*] --> OPENED_GAME_UP
OPENED_GAME_UP --> emptyStock: Player asks to move a card from stock to waste
emptyStock --> OPENED_GAME_DOWN: System shows a card from stock to waste facing up
emptyStock --> emptyWaste: [stock.empty]
emptyWaste --> OPENED_GAME_DOWN: System shows all cards from the waste to the stock facing down
emptyWaste --> S2: [waste.empty]
S2 --> OPENED_GAME_DOWN: System shows no left cards error
OPENED_GAME_DOWN -->[*]

@enduml
