@startuml
[*] --> Initial

state game_over <<choice>>
state show_game <<join>>

Initial --> OPENED_GAME : StartGame
OPENED_GAME --> CLOSED_GAME : AbortGame
OPENED_GAME --> show_game : MovePileToPile
OPENED_GAME --> show_game : MoveFoundationToPile
OPENED_GAME --> show_game : MoveWasteToFoundation
OPENED_GAME --> show_game : MoveWasteToPile
OPENED_GAME --> show_game : MovePileToFoundation
OPENED_GAME --> show_game : MoveStockToWaste
OPENED_GAME --> show_game : MoveWasteToStock
show_game --> game_over : ShowGame

game_over --> CLOSED_GAME : [game_over]
game_over --> OPENED_GAME : [continue game]

CLOSED_GAME --> [*]
@enduml
