@startuml

enum Suit {
 Hearts, Spades, Diamonds, Clubs
}

Card --> Suit

Group -> "*" Card
Group <|-down- Pile
Group <|-down- Stock
Group <|-down- Waste
Group <|-down- Foundation


Tableaux *-down-> "7" Pile
Klondike *-down-> "1" Stock
Klondike *-down-> "1" Waste
Klondike *-down-> "1" Tableaux
Klondike *-down-> "4" Foundation
Klondike *-down-> "1" Player

Foundation --> Suit

Player..>Movement

Movement <|-- FoundationToPile
Movement <|-- PileToFoundation
Movement <|-- PileToPile
Movement <|-- StockToWaste
Movement <|-- WasteToFoundation
Movement <|-- WasteToPile

@enduml


